#語言(英語,繁體中文,簡體中文,巴西葡萄牙語,韓語)
#Language (English,Chinese_TW,Chinese_CN,Portuguese_BR,Korean_KR)
Language: English

#是否啟用HUD
#Whether to enable HUD
enable: false

#HUD更新頻率(單位為秒)
#HUD update frequency (in seconds)
refresh_time: 2